Algoritmo "repitir_ate"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari 
// Descrição   :
// Autor(a)    : Guilherme S.
// Data atual  : 05/05/2025
Var
// Seção de Declarações das variáveis 

   cont, num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


   escreval("Digite o número:")
   leia(num)
   
   repita
    cont <- cont + 1
    escreval(cont)
   ate num = cont

Fimalgoritmo