Algoritmo "posicao2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/05/2025
Var
// Seção de Declarações das variáveis 
   loc: vetor[0..2] de inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   loc[0] <- 10
   loc[1] <- 20
   loc[2] <- 30
   
   escreval("Números da posição 2:", loc[2])

Fimalgoritmo