Algoritmo "enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis
   num: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   num <- 0

   enquanto (num <= 1000) faca
     escreval("O número é", num)
     num <- num + 1
   fimenquanto

Fimalgoritmo