Algoritmo "Valor da area"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : Calcula a area
// Autor(a)    : Guilherme S.
// Data atual  : 17/02/2025
Var
// Seção de Declarações das variáveis 
   valorRaio: real
   
   area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Valor do raio:")
   leia(valorRaio)

   area <- pi * (valorRaio^2)
   
   escreval(area)

Fimalgoritmo