Algoritmo "repita2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme S.
// Data atual  : 29/04/2025
Var
// Seção de Declarações das variáveis 
    num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   repita
   escreval("Digite um número: [0/sair]")
   leia(num)
   escreval("Num:", num)
   ate (num = 0)

Fimalgoritmo